font:
  normal:
    family: Font Awesome
    family: Source Code Pro
    style: Regular
  bold:
    family: Source Code Pro
    style: Bold
  italic:
    family: Source Code Pro
    style: Italic

colors:
  primary:
    background: '#f7f7f7'
    foreground: '#4a4453'
  normal:
    black:   '#090300'
    red:     '#ee2d1e'
    green:   '#01a525'
    yellow:  '#fcac32'
    blue:    '#01a0e4'
    magenta: '#ef388d'
    cyan:    '#06989a'
    white:   '#a5a2a2'
  bright:
    black:   '#5c5855'
    red:     '#ef388d'
    green:   '#3a3432'
    yellow:  '#4a4543'
    blue:    '#807d7c'
    magenta: '#d6d5d4'
    cyan:    '#cdab53'
    white:   '#f7f7f7'
