[theme]
name = "plain"

[theme.overrides]
idle_bg = "#000000"
idle_fg = "#d9d8d8"
info_bg = "#000000"
info_fg = "#d9d8d8"
good_bg = "#000000"
good_fg = "#d9d8d8"
warning_bg  = "#000000"
warning_fg  = "#b58900"
critical_bg = "#000000"
critical_fg = "#dc322f"
separator = "|"
separator_bg = "#000000"
separator_fg = "#000000"

[icons]
name = "awesome5"

[icons.overrides]
memory_mem = ""
cpu = ""
time = ""

[[block]]
block = "custom"
command = "/home/nicolai/dotfiles/scripts/rofication.sh"
interval = 1
on_click= "/usr/bin/rofication-gui.py"

[[block]]
block = "pacman"
interval = 600
format = "{pacman}"
format_singular = "{pacman}"
format_up_to_date = ""
critical_updates_regex = "(linux|linux-lts|linux-zen)"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_total_used_percents}"
format_swap = "{swap_used_percents}"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "sound"
max_vol = 100

[[block]]
block = "temperature"
collapsed = false
scale= "celsius"
interval = 10
format = "{average}"
chip = "*-isa-*"
inputs = ["CPUTIN", "SYSTIN"]

# [[block]]
# block = "bluetooth"
# mac = "DC:2C:26:F4:03:E2"
# format = "K8 {percentage}"
# format_unavailable = ""

# [[block]]
# block = "bluetooth"
# mac = "38:18:4C:AE:20:ED"
# format = "{percentage}"
# format_unavailable = ""

[[block]]
block = "time"
interval = 1
format = "%a, %Y-%m-%d %H:%M"
